columns = ['Ankle Flexion Angle_l',
 'Ankle Flexion Angle_r',
 'Ankle plantar flexion moment_l',
 'Ankle plantar flexion moment_r',
 'Ankle power_l',
 'Ankle power_r',
 'Ankle varus moment_l',
 'Ankle varus moment_r',
 'Foot progression Angle_l',
 'Foot progression Angle_r',
 'Foot progression moment_l',
 'Foot progression moment_r',
 'Hip Flexion Angle_l',
 'Hip Flexion Angle_r',
 'Hip abduction moment_l',
 'Hip abduction moment_r',
 'Hip adduction Angle_l',
 'Hip adduction Angle_r',
 'Hip extension moment_l',
 'Hip extension moment_r',
 'Hip power_l',
 'Hip power_r',
 'Hip rotation Angle_l',
 'Hip rotation Angle_r',
 'Hip rotation moment_l',
 'Hip rotation moment_r',
 'Knee Flexion Angle_l',
 'Knee Flexion Angle_r',
 'Knee adduction moment_l',
 'Knee adduction moment_r',
 'Knee extension moment_l',
 'Knee extension moment_r',
 'Knee power_l',
 'Knee power_r',
 'Knee rotation moment_l',
 'Knee rotation moment_r',
 'Knee varus Angle_l',
 'Knee varus Angle_r',
 'Pelvic Tilt Angle_l',
 'Pelvic Tilt Angle_r',
 'Pelvic obliquity Angle_l',
 'Pelvic obliquity Angle_r',
 'Pelvic rotation Angle_l',
 'Pelvic rotation Angle_r',
 'Tibia torsion Angle_l',
 'Tibia torsion Angle_r']